version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"          # host:container
    depends_on:
      - redis                # wait until redis is ready
  redis:
    image: redis:alpine      # pull Redis image from Docker Hub
